### ISSUE TITLE
[verify] rates/ratio of rx/tx

### ISSUE THREAD

**Issue by nilay994** [nilay994/PercEvite#2]
@ingframin, do the rates (and/or) ratio of rx/tx look correct to you?

1. tx delay: https://github.com/nilay994/PercEvite/blob/e085100b1a52515e8b24453bd13e9e7b3a8c1894/ESP32_firmware/Only_BS/Only_BS.ino#L68

2. rx delay: event driven or driven by blocking delay caused due to: `int numSsid = WiFi.scanNetworks(false, true, true, Ts, ch);` 

3. ratio in use: `50rx-50tx` is good?
https://github.com/nilay994/PercEvite/blob/e085100b1a52515e8b24453bd13e9e7b3a8c1894/ESP32_firmware/Only_BS/Only_BS.ino#L352-L361

**Comment by ingframin** [comment]
Yes, it does. Scan lasts for ~60ms while broadcastSSID lasts for approximately 30ms. It won't be exactly 50-50 but close enough.
What do you mean with point number 2?

**Comment by nilay994** [comment]
Ohh yes! Point 2 was how much time does `scan(ch, 60)` take! Answer was right in front of me. It is clear now. Thank you :)
